import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "@immu/components/index";
import { Murecho, Inter, Ubuntu } from "next/font/google";
import { ProductProvider } from "@immu/contexts/ProductContext";
import FloatingWhatsappButton from "@immu/components/FloatingWhatsappButton";

const murecho = Murecho({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-murecho",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-ubuntu",
});

export const metadata: Metadata = {
  title: "Instituto Manancial Mãos Unidas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`${murecho.variable} ${inter.variable} ${ubuntu.variable}`}>
      <body className="antialiased font-murecho">
        <ProductProvider>
          <Header />
           {/* Rdirecting to whatsapp */}
           <FloatingWhatsappButton />
            {children}
          <Footer />
        </ProductProvider>
      </body>
    </html>
  );
}
